// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Bindings to Ballistics Engine RS
class BallisticsEngine {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  BallisticsEngine(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  /// Creates a new `Ammo` instance
  ffi.Pointer<Ammo> create_ammo(
    double damage,
    double armor_damage,
    double penetration,
    double frag_chance,
  ) {
    _create_ammo ??=
        _dylib.lookupFunction<_c_create_ammo, _dart_create_ammo>('create_ammo');
    return _create_ammo(
      damage,
      armor_damage,
      penetration,
      frag_chance,
    );
  }

  _dart_create_ammo _create_ammo;

  /// Creates a new `Armor` instance
  ffi.Pointer<Armor> create_armor(
    int class_,
    double durability,
    double durability_max,
    double destructibility,
    double blunt_throughput,
  ) {
    _create_armor ??= _dylib
        .lookupFunction<_c_create_armor, _dart_create_armor>('create_armor');
    return _create_armor(
      class_,
      durability,
      durability_max,
      destructibility,
      blunt_throughput,
    );
  }

  _dart_create_armor _create_armor;

  /// Creates a new `PersonHealth` instance
  ffi.Pointer<PersonHealth> create_person_health(
    double head,
    double thorax,
    double stomach,
    double arm_left,
    double arm_right,
    double leg_left,
    double leg_right,
  ) {
    _create_person_health ??= _dylib.lookupFunction<_c_create_person_health,
        _dart_create_person_health>('create_person_health');
    return _create_person_health(
      head,
      thorax,
      stomach,
      arm_left,
      arm_right,
      leg_left,
      leg_right,
    );
  }

  _dart_create_person_health _create_person_health;

  /// Destroys and frees the memory of a `PersonHealth` instance
  void destroy_person_health(
    ffi.Pointer<PersonHealth> health,
  ) {
    _destroy_person_health ??= _dylib.lookupFunction<_c_destroy_person_health,
        _dart_destroy_person_health>('destroy_person_health');
    return _destroy_person_health(
      health,
    );
  }

  _dart_destroy_person_health _destroy_person_health;

  /// Returns the current health status of a `HealthCalculator` instance
  ffi.Pointer<PersonHealth> healh_get_person_health(
    ffi.Pointer<HealthCalculator> calculator,
  ) {
    _healh_get_person_health ??= _dylib.lookupFunction<
        _c_healh_get_person_health,
        _dart_healh_get_person_health>('healh_get_person_health');
    return _healh_get_person_health(
      calculator,
    );
  }

  _dart_healh_get_person_health _healh_get_person_health;

  /// Creates a new `HealthCalculator` instance
  ffi.Pointer<HealthCalculator> health_create_calc(
    ffi.Pointer<PersonHealth> person,
    ffi.Pointer<Ammo> ammo,
  ) {
    _health_create_calc ??=
        _dylib.lookupFunction<_c_health_create_calc, _dart_health_create_calc>(
            'health_create_calc');
    return _health_create_calc(
      person,
      ammo,
    );
  }

  _dart_health_create_calc _health_create_calc;

  /// Destroys and frees the memory of a `HealthCalculator` instance
  void health_destroy_calc(
    ffi.Pointer<HealthCalculator> calculator,
  ) {
    _health_destroy_calc ??= _dylib.lookupFunction<_c_health_destroy_calc,
        _dart_health_destroy_calc>('health_destroy_calc');
    return _health_destroy_calc(
      calculator,
    );
  }

  _dart_health_destroy_calc _health_destroy_calc;

  /// Returns the alive status of a `HealthCalculator` instance
  int health_get_person_alive(
    ffi.Pointer<HealthCalculator> calculator,
  ) {
    _health_get_person_alive ??= _dylib.lookupFunction<
        _c_health_get_person_alive,
        _dart_health_get_person_alive>('health_get_person_alive');
    return _health_get_person_alive(
      calculator,
    );
  }

  _dart_health_get_person_alive _health_get_person_alive;

  /// Processes the impact of ammo on a body zone within a `HealthCalculator` instance
  ffi.Pointer<HealthCalculator> health_impact_on_zone(
    ffi.Pointer<HealthCalculator> calculator,
    int zone,
  ) {
    _health_impact_on_zone ??= _dylib.lookupFunction<_c_health_impact_on_zone,
        _dart_health_impact_on_zone>('health_impact_on_zone');
    return _health_impact_on_zone(
      calculator,
      zone,
    );
  }

  _dart_health_impact_on_zone _health_impact_on_zone;

  /// Resets the calculation of a `HealthCalculator` instance
  ffi.Pointer<HealthCalculator> health_reset_calc(
    ffi.Pointer<HealthCalculator> calculator,
  ) {
    _health_reset_calc ??=
        _dylib.lookupFunction<_c_health_reset_calc, _dart_health_reset_calc>(
            'health_reset_calc');
    return _health_reset_calc(
      calculator,
    );
  }

  _dart_health_reset_calc _health_reset_calc;

  /// Sets new ammo to a existing `HealthCalculator` instance
  ffi.Pointer<HealthCalculator> health_set_ammo(
    ffi.Pointer<HealthCalculator> calculator,
    ffi.Pointer<Ammo> ammo,
  ) {
    _health_set_ammo ??=
        _dylib.lookupFunction<_c_health_set_ammo, _dart_health_set_ammo>(
            'health_set_ammo');
    return _health_set_ammo(
      calculator,
      ammo,
    );
  }

  _dart_health_set_ammo _health_set_ammo;

  /// Creates a new `PenetrationCalculator` instance
  ffi.Pointer<PenetrationCalculator> penetration_create_calc(
    ffi.Pointer<Armor> armor,
    ffi.Pointer<Ammo> ammo,
  ) {
    _penetration_create_calc ??= _dylib.lookupFunction<
        _c_penetration_create_calc,
        _dart_penetration_create_calc>('penetration_create_calc');
    return _penetration_create_calc(
      armor,
      ammo,
    );
  }

  _dart_penetration_create_calc _penetration_create_calc;

  /// Destroys and frees the memory of a `PenetrationCalculator` instance
  void penetration_destroy_calc(
    ffi.Pointer<PenetrationCalculator> calculator,
  ) {
    _penetration_destroy_calc ??= _dylib.lookupFunction<
        _c_penetration_destroy_calc,
        _dart_penetration_destroy_calc>('penetration_destroy_calc');
    return _penetration_destroy_calc(
      calculator,
    );
  }

  _dart_penetration_destroy_calc _penetration_destroy_calc;

  /// Returns the current penetration chance of a `PenetrationCalculator` instance
  double penetration_get_chance(
    ffi.Pointer<PenetrationCalculator> calculator,
  ) {
    _penetration_get_chance ??= _dylib.lookupFunction<_c_penetration_get_chance,
        _dart_penetration_get_chance>('penetration_get_chance');
    return _penetration_get_chance(
      calculator,
    );
  }

  _dart_penetration_get_chance _penetration_get_chance;

  /// Returns the current armor durability of a `PenetrationCalculator` instance
  double penetration_get_durability(
    ffi.Pointer<PenetrationCalculator> calculator,
  ) {
    _penetration_get_durability ??= _dylib.lookupFunction<
        _c_penetration_get_durability,
        _dart_penetration_get_durability>('penetration_get_durability');
    return _penetration_get_durability(
      calculator,
    );
  }

  _dart_penetration_get_durability _penetration_get_durability;

  /// Returns the maximum armor durability of a `PenetrationCalculator` instance
  double penetration_get_durability_max(
    ffi.Pointer<PenetrationCalculator> calculator,
  ) {
    _penetration_get_durability_max ??= _dylib.lookupFunction<
        _c_penetration_get_durability_max,
        _dart_penetration_get_durability_max>('penetration_get_durability_max');
    return _penetration_get_durability_max(
      calculator,
    );
  }

  _dart_penetration_get_durability_max _penetration_get_durability_max;

  /// Sets new ammo to a existing `PenetrationCalculator` instance
  ffi.Pointer<PenetrationCalculator> penetration_set_ammo(
    ffi.Pointer<PenetrationCalculator> calculator,
    ffi.Pointer<Ammo> ammo,
  ) {
    _penetration_set_ammo ??= _dylib.lookupFunction<_c_penetration_set_ammo,
        _dart_penetration_set_ammo>('penetration_set_ammo');
    return _penetration_set_ammo(
      calculator,
      ammo,
    );
  }

  _dart_penetration_set_ammo _penetration_set_ammo;

  /// Sets new armor to a existing `PenetrationCalculator` instance
  ffi.Pointer<PenetrationCalculator> penetration_set_armor(
    ffi.Pointer<PenetrationCalculator> calculator,
    ffi.Pointer<Armor> armor,
  ) {
    _penetration_set_armor ??= _dylib.lookupFunction<_c_penetration_set_armor,
        _dart_penetration_set_armor>('penetration_set_armor');
    return _penetration_set_armor(
      calculator,
      armor,
    );
  }

  _dart_penetration_set_armor _penetration_set_armor;

  /// Sets armor durability of a `PenetrationCalculator` instance
  ffi.Pointer<PenetrationCalculator> penetration_set_durability(
    ffi.Pointer<PenetrationCalculator> calculator,
    double durability,
  ) {
    _penetration_set_durability ??= _dylib.lookupFunction<
        _c_penetration_set_durability,
        _dart_penetration_set_durability>('penetration_set_durability');
    return _penetration_set_durability(
      calculator,
      durability,
    );
  }

  _dart_penetration_set_durability _penetration_set_durability;
}

class Ammo extends ffi.Struct {}

class Armor extends ffi.Struct {}

/// Calculator for calculating the impact of ammunition on a body
class HealthCalculator extends ffi.Struct {}

/// Calculator for calculating the impact of ammunition on armor
class PenetrationCalculator extends ffi.Struct {}

class PersonHealth extends ffi.Struct {
  @ffi.Double()
  double head;

  @ffi.Double()
  double thorax;

  @ffi.Double()
  double stomach;

  @ffi.Double()
  double arm_left;

  @ffi.Double()
  double arm_right;

  @ffi.Double()
  double leg_left;

  @ffi.Double()
  double leg_right;
}

typedef _c_create_ammo = ffi.Pointer<Ammo> Function(
  ffi.Double damage,
  ffi.Double armor_damage,
  ffi.Double penetration,
  ffi.Double frag_chance,
);

typedef _dart_create_ammo = ffi.Pointer<Ammo> Function(
  double damage,
  double armor_damage,
  double penetration,
  double frag_chance,
);

typedef _c_create_armor = ffi.Pointer<Armor> Function(
  ffi.Int32 class_,
  ffi.Double durability,
  ffi.Double durability_max,
  ffi.Double destructibility,
  ffi.Double blunt_throughput,
);

typedef _dart_create_armor = ffi.Pointer<Armor> Function(
  int class_,
  double durability,
  double durability_max,
  double destructibility,
  double blunt_throughput,
);

typedef _c_create_person_health = ffi.Pointer<PersonHealth> Function(
  ffi.Double head,
  ffi.Double thorax,
  ffi.Double stomach,
  ffi.Double arm_left,
  ffi.Double arm_right,
  ffi.Double leg_left,
  ffi.Double leg_right,
);

typedef _dart_create_person_health = ffi.Pointer<PersonHealth> Function(
  double head,
  double thorax,
  double stomach,
  double arm_left,
  double arm_right,
  double leg_left,
  double leg_right,
);

typedef _c_destroy_person_health = ffi.Void Function(
  ffi.Pointer<PersonHealth> health,
);

typedef _dart_destroy_person_health = void Function(
  ffi.Pointer<PersonHealth> health,
);

typedef _c_healh_get_person_health = ffi.Pointer<PersonHealth> Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _dart_healh_get_person_health = ffi.Pointer<PersonHealth> Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _c_health_create_calc = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<PersonHealth> person,
  ffi.Pointer<Ammo> ammo,
);

typedef _dart_health_create_calc = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<PersonHealth> person,
  ffi.Pointer<Ammo> ammo,
);

typedef _c_health_destroy_calc = ffi.Void Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _dart_health_destroy_calc = void Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _c_health_get_person_alive = ffi.Int32 Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _dart_health_get_person_alive = int Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _c_health_impact_on_zone = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
  ffi.Uint32 zone,
);

typedef _dart_health_impact_on_zone = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
  int zone,
);

typedef _c_health_reset_calc = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _dart_health_reset_calc = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
);

typedef _c_health_set_ammo = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
  ffi.Pointer<Ammo> ammo,
);

typedef _dart_health_set_ammo = ffi.Pointer<HealthCalculator> Function(
  ffi.Pointer<HealthCalculator> calculator,
  ffi.Pointer<Ammo> ammo,
);

typedef _c_penetration_create_calc = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<Armor> armor,
  ffi.Pointer<Ammo> ammo,
);

typedef _dart_penetration_create_calc = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<Armor> armor,
  ffi.Pointer<Ammo> ammo,
);

typedef _c_penetration_destroy_calc = ffi.Void Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _dart_penetration_destroy_calc = void Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _c_penetration_get_chance = ffi.Double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _dart_penetration_get_chance = double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _c_penetration_get_durability = ffi.Double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _dart_penetration_get_durability = double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _c_penetration_get_durability_max = ffi.Double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _dart_penetration_get_durability_max = double Function(
  ffi.Pointer<PenetrationCalculator> calculator,
);

typedef _c_penetration_set_ammo = ffi.Pointer<PenetrationCalculator> Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  ffi.Pointer<Ammo> ammo,
);

typedef _dart_penetration_set_ammo = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  ffi.Pointer<Ammo> ammo,
);

typedef _c_penetration_set_armor = ffi.Pointer<PenetrationCalculator> Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  ffi.Pointer<Armor> armor,
);

typedef _dart_penetration_set_armor = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  ffi.Pointer<Armor> armor,
);

typedef _c_penetration_set_durability = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  ffi.Double durability,
);

typedef _dart_penetration_set_durability = ffi.Pointer<PenetrationCalculator>
    Function(
  ffi.Pointer<PenetrationCalculator> calculator,
  double durability,
);
