name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk

      - name: Flutter action
        uses: subosito/flutter-action@v2.4.0

      - run: |
              dart --version
              flutter --version

      - run: flutter pub get

      - name: Run Analyze
        run: flutter analyze --no-fatal-infos

      # - name: Run Test
      #   run: flutter test
